# Generated by Django 3.1.5 on 2021-02-03 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Timestamp', models.DateTimeField(verbose_name='timestamp')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('Id', models.TextField(primary_key=True, serialize=False)),
                ('Kind', models.TextField(verbose_name='kind')),
                ('JsonData', models.TextField(verbose_name='jsondata')),
            ],
        ),
        migrations.DeleteModel(
            name='Greeting',
        ),
        migrations.AddField(
            model_name='history',
            name='Song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.song'),
        ),
    ]
