# Generated by Django 3.1.5 on 2021-02-06 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_history_has_timestamp_as_id'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='song',
            constraint=models.UniqueConstraint(fields=('Id', 'Kind'), name='unique_kind_id'),
        ),
    ]
